### ISSUE TITLE
large version of friendster

### ISSUE THREAD

**Issue by Weesley743** [PurdueMINDS/GNNsMiscalibrated#1]
Hi, I am looking for a large-scale graph datasets. Can you share the original version of the friendster(6M) with features and labels?

**Comment by leolvt** [comment]
Thank you for your interest! Unfortunately, the original Friendster dataset is not yet publicly available, as we are still working with IRB on releasing the full data.

**Comment by Weesley743** [comment]
Thanks for your reply.
